import { describe,it,expect } from 'vitest';
import chart from '../public/chart.json';
import {Score,grade,validateChart,Engine,Random,Zones,travel,swept,direction,STEP} from '../src/core';
describe('adopted gameplay rules',()=>{
 it('validates 151 chart targets and independent maximum score',()=>{expect(validateChart(chart).targets.at(-1)?.at).toBe(179625);const s=new Score();for(let i=0;i<151;i++)s.judge('Perfect');expect(s.match).toBe(23575);expect(s.total(180000)).toBe(41575);expect(s.total(1999)-s.match).toBe(100);});
 it.each([[0,'Perfect'],[60,'Perfect'],[-60,'Perfect'],[60.001,'Great'],[120,'Great'],[-120,'Great'],[120.001,'Good'],[200,'Good'],[-200,'Good'],[200.001,'Miss']])('grades %s as %s',(ms,g)=>expect(grade(Number(ms))).toBe(g));
 it('rejects invalid chart overlaps and metadata',()=>{expect(()=>validateChart({...chart,maxScore:1})).toThrow();expect(()=>validateChart({...chart,targets:chart.targets.map((t,i)=>i===0?{...t,at:2001}:t)})).toThrow();});
 it('tracks separate health, recovery and score combos',()=>{const s=new Score();for(let i=0;i<4;i++)s.judge('Great');expect(s.life).toBe(68);s.judge('Perfect');expect(s.life).toBe(74);s.judge('Good');expect(s.recovery).toBe(0);expect(s.combo).toBe(6);for(let i=0;i<4;i++)s.judge('Miss');expect(s.life).toBe(18);expect(s.combo).toBe(0);s.judge('Good');s.judge('Miss');expect(s.life).toBe(10);s.judge('Miss');expect(s.life).toBe(0);});
 it('normalizes diagonals and preserves reflected speed',()=>{expect(Math.hypot(...Object.values(direction(1,1)))).toBeCloseTo(1);const b={id:0,x:98,y:98,vx:10,vy:10,activeAt:0};travel(b,.2);expect(b.vx).toBe(-10);expect(b.vy).toBe(-10);expect(b.x).toBeCloseTo(96.8);expect(b.y).toBeCloseTo(96.8);});
 it('detects high-speed swept contact and rejects separated paths',()=>{expect(swept({x:50,y:50},{x:50,y:50},{x:0,y:50},{x:100,y:50},3.1)).toBe(true);expect(swept({x:50,y:54},{x:50,y:54},{x:0,y:50},{x:100,y:50},3.1)).toBe(false);});
 it('reflects identically under frame subdivision',()=>{const a={id:0,x:90,y:80,vx:65,vy:13,activeAt:0},b={...a};travel(a,3);for(let i=0;i<180;i++)travel(b,1/60);expect(b.x).toBeCloseTo(a.x);expect(b.y).toBeCloseTo(a.y);expect(b.vx).toBe(a.vx);});
 it('keeps the prior zone within the hairline and switches outside',()=>{const z=new Zones(new Random(1),new Random(2));z.update(45000);z.current=0;expect(z.resolve({x:50.0625,y:20})).toBe(0);expect(z.resolve({x:50.0626,y:20})).toBe(1);expect(z.resolve({x:49.9375,y:20})).toBe(1);expect(z.resolve({x:49.9374,y:20})).toBe(0);});
 it('starts all timers at 50.300 and splits only the penalized zone',()=>{const z=new Zones(new Random(1),new Random(2));z.update(45000);expect(z.zones.map(t=>t.next)).toEqual([50300,50300,50300,50300]);z.update(50300);const colors=z.zones.map(t=>t.color);z.reroll(2,51000);expect(z.zones[2].next).toBe(56300);expect(z.zones[0].next).toBe(55600);expect(z.zones[2].color).not.toBe(colors[2]);expect(z.zones[0].color).toBe(colors[0]);});
 it('penalty fade starts from the current composite and keeps logical color separate',()=>{const z=new Zones(new Random(1),new Random(2));z.update(45000);const before=z.display(0,47000);z.reroll(0,47000);expect(z.display(0,47000)).toEqual(before);const mid=z.display(0,47500);z.reroll(0,47500);expect(z.display(0,47500)).toEqual(mid);expect(z.display(0,48500)).not.toEqual(mid);});
 it('replays seed, input, balls and targets deterministically',()=>{const a=new Engine(chart,1234),b=new Engine(chart,1234);for(let i=0;i<1200;i++){a.move=b.move={x:Math.sin(i/40)>0?1:-1,y:0};a.step();b.step();}expect(a).toEqual(b);expect(new Engine(chart,5678).balls).not.toEqual(new Engine(chart,1234).balls);});
 it('locks forbidden state and auto-awards a perfect on no touch',()=>{const e=new Engine(chart,42);e.balls=[];e.targets[0].color=e.zones.zones[0].color;while(e.time<1800)e.step();expect(e.targets[0].forbidden).toBe(true);while(e.time<2210)e.step();expect(e.score.counts.Perfect).toBe(1);});
 it('forbidden touch rerolls the locked zone and records a miss',()=>{const e=new Engine(chart,42);e.balls=[];e.targets[0].color=e.zones.zones[0].color;while(e.time<1900)e.step();const old=e.zones.zones[0].color;e.tap(0);e.step();expect(e.score.counts.Miss).toBe(1);expect(e.zones.zones[0].color).not.toBe(old);expect(e.cryUntil).toBeGreaterThan(e.time);});
 it('exercises a full 180-second chart with collision-free test fixture',()=>{const e=new Engine(chart,999);for(let i=0;i<10800;i++){e.balls=[];for(const t of e.targets)if(!t.judged&&t.locked&&!t.forbidden&&Math.abs(e.time-t.at)<=STEP/2)e.tap(t.id);e.step();}expect(e.end).toBe('chart_complete');expect(e.score.counts.Perfect).toBe(151);expect(e.score.total(e.time)).toBe(41575);});
});
